version: '3.3'

services:
  backend:
    container_name: kpd-backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    ports:
      - '4000:3001'
    networks:
      - backend-database
    depends_on:
      - postgres

  postgres:
    container_name: database
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend-database

  frontend:
    container_name: kpd-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8081:80'

volumes:
  pg_data:
    driver: local

networks:
  backend-database: {}